/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yyz_test_jnidemo_JniTest */

#ifndef _Included_com_yyz_test_jnidemo_JniTest
#define _Included_com_yyz_test_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yyz_test_jnidemo_JniTest
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yyz_test_jnidemo_JniTest_getHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
